### ISSUE TITLE
502 for services behind LB

### ISSUE THREAD

**Issue by makp0** [GuyBarros/terraform-hcp-demostack-aws#24]
http://fabio.primarystack.*:9999
https://nomad.primarystack.*:4646
http://traefik.primarystack.*:8080

All these services show error 502 from the start.

**Comment by GuyBarros** [comment]
pardon the delay, fabio and traefik need to be deployed  on nomad  for those LBs to work, and the Nomad LB takes a little while to spin up.

https://github.com/GuyBarros/nomad_jobs/blob/master/fabio-lb.nomad

https://github.com/GuyBarros/nomad_jobs/blob/master/traefik.nomad

is the nomad deployment failing ?
